package com.teste.pratico.db;

import java.sql.SQLException;

public class BuildTable extends DbConection{

    private final String tableVagas = "CREATE TABLE IF NOT EXISTS VAGAS ("
            + "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "inicio TIMESTAMP,"
            + "fim TIMESTAMP,"
            + "quantidade INTEGER);";

    private final String tableSolicitantes = "CREATE TABLE IF NOT EXISTS SOLICITANTES ("
            + "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "nome VARCHAR(50) NOT NULL);";

    private final String tableAgendamentos = "CREATE TABLE IF NOT EXISTS AGENDAMENTOS ("
            + "data_agendamento TIMESTAMP,"
            + "numero_agendamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "motivo VARCHAR(100),"
            + "solicitante_id INTEGER,"
            + "FOREIGN KEY (solicitante_id) REFERENCES SOLICITANTES(id));";


   public void contructTable() throws SQLException {
       setScriptddl(tableVagas);
       System.out.println("Tabela Vagas criada!!!");

       setScriptddl(tableSolicitantes);
       System.out.println("Tabela Solicitantes criada!!!");

       setScriptddl(tableAgendamentos);
       System.out.println("Tabela Agendamento criada!!!");

   }
}
